version: '3'

services:
  aq:
    image: airqualitydashboard:latest
    container_name: airqualitydashboard
    build: ./docker
    restart: always
    user: root
    ports:
      - "8501:8501"
    volumes:
      - /gis/air_quality/data:/app/Data/Model_Data:ro
      - /gis/air_quality/scratch:/app/scratch
      - /gis/air_quality/app/AirQualityDashboard:/app
    command: streamlit run Streamlit_app.py

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "81:81"
    depends_on:
      - aq
