# https://thatdevopsguy.medium.com/how-to-create-a-static-web-server-for-html-with-nginx-99bf8226bce6

FROM nginx:1.23.1-alpine

# config
COPY ./nginx.conf /etc/nginx/nginx.conf

# Content, comment out the ones you don't need!
#COPY ./*.html /usr/share/nginx/html